# Generated by Django 5.1.1 on 2024-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_phone_number_user_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('superadmin', 'superadmin'), ('user', 'user'), ('vendor', 'vendor')], default='user', max_length=25),
        ),
    ]
