# Generated by Django 5.1.1 on 2024-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staffuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuserprofile',
            name='designation',
            field=models.CharField(blank=True, choices=[('chat_assistant', 'chat_assistant'), ('chatbot', 'chatbot'), ('supervisor', 'supervisor'), ('regular', 'regular')], max_length=255, null=True),
        ),
    ]
