# Generated by Django 5.1.1 on 2024-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue_type',
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_types',
            field=models.ManyToManyField(blank=True, null=True, to='support.generalissues'),
        ),
    ]
