# Generated by Django 5.1.1 on 2024-11-06 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_ticket_issue_type_ticket_issue_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='issue_types',
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.generalissues'),
        ),
    ]
