# List of items generated from data.txt
items = [
    '"Fruit Chaat',
    'Khasta Kachori',
    'Samosa Chaat',
    'Kesar Milk',
    'Shahi Tukda',
    'Pani Puri',
    'Bhel Puri',
    'Sev Puri',
    'Dahi Puri',
    'Aloo Tikki Chaat',
    'Soda',
    'Thandai',
    'Falooda',
    'Nimbu Pani',
    'Mango Lassi',
    'Kesar Lassi',
    'Badaam Milk',
    'Ice Cream Roll',
    'Chocolate Ice Cream',
    'Vermicelli Pudding',
    'Gajar Halwa',
    'Chana Dal Halwa',
    'Sooji Halwa',
    'Methi Thepla',
    'Dhokla',
    'Khandvi',
    'Methi Malai Murg',
    'Dal Bukhara',
    'Paneer Tikka',
    'Kadai Chicken',
    'Palak Paneer',
    'Baingan Bharta',
    'Aloo Gobi',
    'Mixed Vegetable Curry',
    'Paneer Kofta',
    'Malai Kofta',
    'Chole Bhature',
    'Bhindi Masala',
    'Vegetable Manchurian',
    'Chili Paneer',
    'Paneer Pakora',
    'Dahi Bhalla',
    'Paneer Butter Masala',
    'Palak Chole',
    'Khichdi',
    'Vegetable Upma',
    'Bhel',
    'Pav Bhaji',
    'Chaat Masala',
    'Kachori',
    'Pakora',
    'Masala Dosa',
    'Onion Dosa',
    'Chili Dosa',
    'Rawa Dosa',
    'Cheese Dosa',
    'Sambhar Dosa',
    'Pesarattu Dosa',
    'Egg Dosa',
    'Veggie Burger',
    'Beetroot Burger',
    'Paneer Tikka Burger',
    'Chana Chaat',
    'Kathi Roll',
    'Cheese Roll',
    'Chicken Roll',
    'Tandoori Chicken Roll',
    'Egg Roll',
    'Veg Roll',
    'Paneer Kathi Roll',
    'Mushroom Roll',
    'Chili Garlic Noodles',
    'Hakka Noodles',
    'Szechuan Noodles',
    'Garlic Noodles',
    'Tomato Soup',
    'Vegetable Soup',
    'Lentil Soup',
    'Mushroom Soup',
    'Hot and Sour Soup',
    'Corn Soup',
    'Paneer Biryani',
    'Egg Biryani',
    'Vegetable Pulao',
    'Methi Rice',
    'Jeera Rice',
    'Curd Rice',
    'Chili Garlic Rice',
    'Garlic Fried Rice',
    'Coconut Rice',
    'Lemon Rice',
    'Pongal',
    'Khar',
    'Khichuri',
    'Tomato Rice',
    'Sambar Rice',
    'Dal Rice',
    'Vegetable Khichdi',
    'Dal Makhani',
    'Tandoori Roti',
    'Chapati',
    'Butter Naan',
    'Garlic Naan',
    'Stuffed Naan',
    'Missi Roti',
    'Jowar Roti',
    'Bajra Roti',
    'Ragi Roti',
    'Cabbage Pakora',
    'Spinach Pakora',
    'Onion Bhaji',
    'Dhokla',
    'Khandvi',
    'Sukhdi',
    'Chikki',
    'Kaju Katli',
    'Dahi Puri',
    'Aloo Tikki',
    'Veggie Tikki',
    'Sooji Dhokla',
    'Methi Dhokla',
    'Masala Papad',
    'Papad Chaat',
    'Khichu',
    'Dahi Puri',
    'Dahi Vada',
    'Gobi Manchurian',
    'Palak Chaat',
    'Vegetable Samosa',
    'Egg Samosa',
    'Dumplings',
    'Veg Momos',
    'Chicken Momos',
    'Prawn Momos',
    'Pork Momos',
    'Fruit Salad',
    'Tandoori Veggie Skewers',
    'Chicken Seekh Kebabs',
    'Mutton Seekh Kebabs',
    'Fish Seekh Kebabs',
    'Paneer Seekh Kebabs',
    'Masala Seekh Kebabs',
    'Sikh Kebab',
    'Fried Fish',
    'Fish Fry',
    'Tandoori Prawns',
    'Grilled Fish',
    'Prawn Curry',
    'Fish Curry',
    'Prawn Biryani',
    'Goan Fish Curry',
    'Mangalorean Fish Curry',
    'Egg Curry',
    'Chicken Curry',
    'Mutton Curry',
    'Vegetable Curry',
    'Methi Chicken',
    'Tandoori Chicken',
    'Butter Chicken',
    'Kadai Paneer',
    'Palak Paneer',
    'Butter Dal',
    'Dal Tadka',
    'Palak Chole',
    'Chole Rice',
    'Chole Kulche',
    'Pav Bhaji',
    'Dum Aloo',
    'Baida Roti',
    'Chicken Pulao',
    'Vegetable Pulao',
    'Keema Pulao',
    'Fish Pulao',
    'Chana Pulao',
    'Paneer Pulao',
    'Saffron Pulao',
    'Coconut Pulao',
    'Vegetable Curry',
    'Vegetable Biryani',
    'Chicken Biryani',
    'Mutton Biryani',
    'Kachori Sabzi',
    'Rajma Rice',
    'Methi Aloo',
    'Bisi Bele Bath',
    'Bisibelebath',
    'Avial',
    'Pineapple Fried Rice',
    'Masala Rice',
    'Kashmiri Pulao',
    'Vegetable Jalfrezi',
    'Vegetable Stir Fry',
    'Tofu Stir Fry',
    'Vegetable Manchurian',
    'Paneer Manchurian',
    'Chili Chicken',
    'Prawn Masala',
    'Veg Pakoda',
    'Chicken Pakoda',
    'Mutton Seekh Kebabs',
    'Biryani',
    'Pulao',
    'Hyderabadi Biryani',
    'Lucknowi Biryani',
    'Chicken Biryani',
    'Mutton Biryani',
    'Veg Biryani',
    'Paneer Biryani',
    'Kashmiri Biryani',
    'Biryani Pot',
    'Khichdi',
    'Masala Khichdi',
    'Jeera Rice',
    'Steamed Rice',
    'Puliyodarai',
    'Curd Rice',
    'Kadhi Pakora',
    'Bonda Soup',
    'Sambar Rice',
    'Chitranna',
    'Karnataka Meals',
    'Pongal',
    'Khar',
    'Pithla Bhakri',
    'Puran Poli',
    'Gulab Jamun',
    'Jalebi',
    'Rasgulla',
    'Rasmalai',
    'Kheer',
    'Rabri',
    'Barfi',
    'Ladoo',
    'Motichoor Ladoo',
    'Chum Chum',
    'Peda',
    'Kaju Katli',
    'Chikki',
    'Chocolate Samosa',
    'Nutella Dosa',
    'Bhelpuri',
    'Sev Tameta',
    'Kachori Sabzi',
    'Raj Kachori',
    'Methi Thepla',
    'Soya Chaap',
    'Dumplings',
    'Spring Roll',
    'Tandoori Momos',
    'Tandoori Fish',
    'Fish Tikka',
    'Seafood Biryani',
    'Fish Curry',
    'Prawn Masala',
    'Bamboo Rice',
    'Idiyappam',
    'Appam',
    'Puttu',
    'Neer Dosa',
    'Pongal Vadai',
    'Kozhukkatta',
    'Kozhi Varutharacha Curry',
    'Kappa Biriyani',
    'Aloo Chaat',
    'Dahi Ke Kebab',
    'Patiala Chicken',
    'Chicken Tikka Masala',
    'Paneer Tikka Masala',
    'Chettinad Chicken',
    'Mutton Curry',
    'Egg Curry',
    'Dal Makhani',
    'Rajma',
    'Palak Dal',
    'Tomato Rasam',
    'Pineapple Fried Rice',
    'Thai Curry',
    'Tandoori Chicken',
    'Chicken Seekh Kebab',
    'Mutton Seekh Kebab',
    'Keema Pav',
    'Egg Bhurji Pav',
    'Veggie Burger',
    'Chicken Burger',
    'Pav Bhaji',
    'Vada Pav',
    'Masala Pav',
    'Dabeli Pav',
    'Dosa Corner',
    'Dhokla Corner',
    'Fried Idli',
    'Paneer Pakoda',
    'Aloo Pakora',
    'Onion Pakoda',
    'Prawn Pakora',
    'Chili Fish',
    'Chicken Wontons',
    'Momos',
    'Sweet Potato Chaat',
    'Bhel',
    'Sev Khaman',
    'Pani Puri Wali',
    'Samosa Chaat',
    'Khichu',
    'Thukpa',
    'Tibetan Momos',
    'Korean Corn Dog',
    'Kathi Roll',
    'Sushi',
    'Pasta',
    'Spaghetti',
    'Pav Bhaji Pizza',
    'Dhokla Pizza',
    'Cheesy Maggi',
    'Cheese Burst Dosa',
    'Cheesy Fries',
    'Choco Lava Cake',
    'Gulab Jamun Shake',
    'Fruit Chaat',
    'Aloo Methi',
    'Nimbu Pani',
    'Lassi',
    'Chaas',
    'Sugarcane Juice',
    'Nariyal Pani',
    'Ganne Ka Juice',
    'Mango Shake',
    'Mixed Fruit Juice',
    'Cold Coffee',
    'Iced Tea',
    'Masala Chai',
    'Kashmiri Chai',
    'Bun Maska',
    'Pav Bhaji',
    'Chowmein',
    'Lemon Rice',
    'Sooji Halwa',
    'Kesar Pista',
    'Khoya',
    'Sooji Dhokla',
    'Veg Khichdi',
    'Ghar Ka Khana',
    'Fried Rice',
    'Tandoori Chai',
    'Kebabs',
    'Tandoor Fish',
    'Schezwan Fried Rice',
    'Pav Bhaji Biryani',
    'Aloo Gobi',
    'Bitter Gourd Fry',
    'Fenugreek Leaves',
    'Beetroot Cutlet',
    'Vegetable Pulao',
    'Tomato Rice',
    'Vermicelli Upma',
    'Chitranna',
    'Chow Chow Bath',
    'Bisi Bele Bath',
    'Puliyogare',
    'Cabbage Rice',
    'Curd Vada',
    'Paneer Bhurji',
    'Dal Tadka',
    'Pongal',
    'Thali',
    'Lunch Box',
    'Jowar Bhakri',
    'Ragi Roti',
    'Baida Roti',
    'Stuffed Paratha',
    'Cheese Burst Pizza',
    'Stuffed Naan',
    'Hot Dog',
    'Choco Tacos',
    'Fruit Ice Cream',
    'Raita',
    'Paneer Raita',
    'Boondi Raita',
    'Salad',
    'Chaat Counter',
    'Dahi Chaat',
    'Rice Bowl',
    'Vegetable Bowl',
    'Egg Bowl',
    'Chicken Bowl',
    'Paneer Bowl',
    'Grilled Sandwich',
    'Veg Grill Sandwich',
    'Cheese Sandwich',
    'Veggie Wrap',
    'Stuffed Roll',
    'Chicken Roll',
    'Paneer Wrap',
    'Mini Idli',
    'Sambar Idli',
    'Cheese Idli',
    'Noodles',
    'Palak Chaat',
    'Kadi',
    'Daal Baati',
    'Hakka Noodles',
    'Chowmein',
    'Biryani Roll',
    'Veg Rolls',
    'Chicken Nuggets',
    'Chili Chicken',
    'Noodles Salad',
    'Spring Roll',
    'Pasta Salad',
    'Veg Puffs',
    'Chicken Puffs',
    'Cheese Puffs',
    'Egg Puffs',
    'Chocolate Dosa',
    'Nutella Pancakes',
    'Pineapple Pastry',
    'Mango Pastry',
    'Strawberry Cake',
    'Cupcake',
    'Brownie',
    'Fried Cheesecake',
    'Chocolate Tarts',
    'Fruit Tart',
    'Mochi Ice Cream',
    'Gelato',
    'Ice Cream Sundae',
    'Milkshake',
    'Banana Split',
    'Choco Chip Cookie',
    'Red Velvet Cake',
    'Coffee Cake',
    'Cheesecake',
    'Mousse',
    'Caramel Custard',
    'Custard Apple Shake',
    'Fruit Custard',
    'Gajar Ka Halwa',
    'Kashmiri Kebab',
    'Szechuan Chicken',
    'Cheese Dosa',
    'Stuffed Paneer Dosa',
    'Fish Curry Rice',
    'Prawn Fried Rice',
    'Mixed Vegetable Stir-Fry',
    'Paneer Butter Masala',
    'Vegetable Biryani',
    'Sweet Corn Soup',
    'Hot and Sour Soup',
    'Tom Yum Soup',
    'Spicy Noodles',
    'Dal Baati Churma',
    'Chole Bhature',
    'Rajma Chawal',
    'Kadhi Chawal',
    'Pindi Chana',
    'Aloo Tikki Chaat',
    'Paneer Tikka',
    'Hara Bhara Kebab',
    'Vegetable Kebab',
    'Tandoori Paneer',
    'Chana Chaat',
    'Dhokla',
    'Khandvi',
    'Patra',
    'Fafda Jalebi',
    'Kachori',
    'Mawa Kachori',
    'Dal Kachori',
    'Pyaaz Kachori',
    'Moong Dal Halwa',
    'Gajar Halwa',
    'Doodh Jalebi',
    'Roti Sabzi',
    'Tandoori Roti',
    'Naan',
    'Butter Naan',
    'Garlic Naan',
    'Tandoori Paratha',
    'Lachha Paratha',
    'Aloo Paratha',
    'Paneer Paratha',
    'Gobi Paratha',
    'Methi Paratha',
    'Chur Chur Naan',
    'Khasta Paratha',
    'Bhakri',
    'Thepla',
    'Bajra Roti',
    'Jowar Roti',
    'Missi Roti',
    'Makai Roti',
    'Thalipeeth',
    'Sarson Ka Saag',
    'Baigan Bharta',
    'Aloo Gobhi',
    'Aloo Methi',
    'Aloo Palak',
    'Palak Paneer',
    'Matar Paneer',
    'Shahi Paneer',
    'Paneer Bhurji',
    'Paneer Butter Masala',
    'Kofta',
    'Vegetable Handi',
    'Navratan Korma',
    'Bhindi Fry',
    'Methi Malai Mutter',
    'Kadhai Paneer',
    'Dum Aloo',
    'Baida Roti',
    'Mutton Rogan Josh',
    'Keema Naan',
    'Mutton Nihari',
    'Beef Nihari',
    'Chicken Bhuna',
    'Mutton Bhuna',
    'Chicken Kebab Paratha',
    'Egg Kebab',
    'Shawarma Paratha',
    'Mughlai Paratha',
    'Rumali Roti',
    'Baklava',
    'Halwa Puri',
    'Gobi Manchurian',
    'Paneer Manchurian',
    'Chicken Manchurian',
    'Veg Hakka Noodles',
    'Chicken Hakka Noodles',
    'Paneer Fried Rice',
    'Veg Fried Rice',
    'Egg Fried Rice',
    'Chicken Fried Rice',
    'Schezwan Fried Rice',
    'Schezwan Noodles',
    'Chilli Garlic Noodles',
    'Mushroom Noodles',
    'Chilli Garlic Fried Rice',
    'Paneer Chili',
    'Vegetable Spring Roll',
    'Chicken Spring Roll',
    'Egg Spring Roll',
    'Sweet Corn Soup',
    'Hot and Sour Soup',
    'Manchow Soup',
    'Tomato Soup',
    'Vegetable Soup',
    'Chicken Soup',
    'Paya Soup',
    'Dosa',
    'Masala Dosa',
    'Plain Dosa',
    'Set Dosa',
    'Onion Dosa',
    'Rava Dosa',
    'Mysore Masala Dosa',
    'Cheese Dosa',
    'Paneer Dosa',
    'Chicken Dosa',
    'Egg Dosa',
    'Butter Dosa',
    'Podi Dosa',
    'Neer Dosa',
    'Uttapam',
    'Onion Uttapam',
    'Tomato Uttapam',
    'Vegetable Uttapam',
    'Cheese Uttapam',
    'Paneer Uttapam',
    'Idli',
    'Vada',
    'Medu Vada',
    'Sambar Vada',
    'Rasam Vada',
    'Masala Vada',
    'Dal Vada',
    'Paruppu Vada',
    'Bondas',
    'Punugulu',
    'Sabudana Vada',
    'Batata Vada',
    'Aloo Bonda',
    'Paneer Bonda',
    'Masala Bonda',
    'Moong Dal Bonda',
    'Vegetable Bonda',
    'Samosa Chaat',
    'Kachori Chaat',
    'Aloo Chaat',
    'Bhel Puri',
    'Sev Puri',
    'Pani Puri',
    'Dahi Puri',
    'Ragda Pattice',
    'Dahi Bhalla',
    'Chana Jor Garam',
    'Pav Bhaji',
    'Misal Pav',
    'Usal Pav',
    'Vada Pav',
    'Dabeli',
    'Aloo Frankie',
    'Paneer Frankie',
    'Cheese Frankie',
    'Egg Frankie',
    'Chicken Frankie',
    'Mutton Frankie',
    'Fish Frankie',
    'Mushroom Frankie',
    'Soya Chaap Frankie',
    'Chilli Paneer',
    'Chilli Chicken',
    'Chicken Tikka Roll',
    'Chicken Shawarma',
    'Lamb Shawarma',
    'Falafel',
    'Hummus with Pita',
    'Biryani',
    'Vegetable Biryani',
    'Egg Biryani',
    'Mutton Biryani',
    'Beef Biryani',
    'Fish Fry',
    'Pomfret Fry',
    'Surmai Fry',
    'Bangda Fry',
    'Prawn Fry',
    'Fish Curry',
    'Goan Fish Curry',
    'Malvani Fish Curry',
    'Crab Curry',
    'Tandoori Chicken',
    'Grilled Chicken',
    'Barbecue Chicken',
    'Fried Chicken',
    'Butter Chicken',
    'Chicken Curry',
    'Kofta Curry',
    'Lamb Curry',
    'Nihari',
    'Korma',
    'Chicken Malai Tikka',
    'Chicken Reshmi Kebab',
    'Shami Kebab',
    'Galouti Kebab',
    'Seekh Kebab',
    'Kakori Kebab',
    'Beef Seekh Kebab',
    'Mutton Seekh Kebab',
    'Keema Pao',
    'Egg Bhurji',
    'Anda Pao',
    'Keema Samosa',
    'Mutton Samosa',
    'Chicken Samosa',
    'Egg Samosa',
    'Prawns Samosa',
    'Veggie Samosa',
    'Mutton Kheema Pav',
    'Paneer Kathi Roll',
    'Tawa Pulao',
    'Prawn Pulao',
    'Chicken Pulao',
    'Fish Pulao',
    'Vegetable Pulao',
    'Mutton Pulao',
    'Kheer',
    'Phirni',
    'Gulab Jamun',
    'Rasgulla',
    'Jalebi',
    'Kulfi',
    'Falooda',
    'Ice Cream',
    'Rabri',
    'Mithai',
    'Besan Ladoo',
    'Motichoor Ladoo',
    'Kaju Katli',
    'Peda',
    'Barfi',
    'Ghevar',
    'Imarti',
    'Chum Chum',
    'Halwa',
    'Sohan Papdi',
    'Shahi Tukda',
    'Malpua',
    'Rasmalai',
    'Kesari Bath',
    'Payasam',
    'Shrikhand',
    'Kharwas',
    'Basundi',
    'Mishti Doi',
    'Coconut Ladoo',
    'Modak',
    'Puran Poli',
    'Chikki',
    'Tilgul',
    'Patishapta',
    'Kulhad Milk',
    'Masala Milk',
    'Rose Milk',
    'Aloo Tikki Chaat',
    'Dahi Bhalla',
    'Chowmein',
    'Chili Garlic Noodles',
    'Veg Fried Rice',
    'Hakka Noodles',
    'Manchurian',
    'Paneer Chilli',
    'Gobi Manchurian',
    'Chicken 65',
    'Kathi Roll',
    'Egg Kathi Roll',
    'Paneer Kathi Roll',
    'Mutton Kathi Roll',
    'Cheese Momos',
    'Fried Momos',
    'Steamed Momos',
    'Tandoori Momos',
    'Chocolate Momos',
    'Wheat Momos',
    'Vegetarian Momos',
    'Chicken Momos',
    'Pork Momos',
    'Lamb Momos',
    'Corn Momos',
    'Jalebi Rabri',
    'Fried Ice Cream',
    'Brownie with Ice Cream',
    'Fruit Salad',
    'Fruit Chaat',
    'Sprouts Chaat',
    'Egg Curry',
    'Prawn Biryani',
    'Fish Biryani',
    'Samosa Chaat',
    'Ragda Pattice',
    'Bhakri',
    'Fafda',
    'Dhokla',
    'Khandvi',
    'Patra',
    'Gathiya',
    'Khakhra',
    'Thepla',
    'Gujarati Thali',
    'Bajra Roti',
    'Methi Paratha',
    'Litti Chokha',
    'Dal Baati Churma',
    'Ker Sangri',
    'Aloo Kachori',
    'Sabudana Vada',
    'Dabeli',
    'Kutchi Dabeli',
    'Pav Bhaji',
    'Misal Pav',
    'Vada Pav',
    'Bhajji Pav',
    'Sabudana Khichdi',
    'Puri Sabzi',
    'Paneer Tikka Roll',
    'Bhel Puri',
    'Sev Puri',
    'Papdi Chaat',
    'Dahi Puri',
    'Masala Puri',
    'Tokri Chaat',
    'Dhokla Sandwich',
    'Corn Bhel',
    'Batata Wada',
    'Vermicelli Upma',
    'Sambhar Vada',
    'Rava Dosa',
    'Neer Dosa',
    'Akki Roti',
    'Thalipeeth',
    'Chole Kulche',
    'Pindi Chole',
    'Matar Kulcha',
    'Bedmi Puri',
    'Chana Puri',
    'Paneer Paratha',
    'Mooli Paratha',
    'Onion Paratha',
    'Dal Paratha',
    'Gobi Paratha',
    'Cheese Paratha',
    'Chocolate Paratha',
    'Pizza Paratha',
    'Veg Seekh Kebab',
    'Mushroom Kebab',
    'Jackfruit Kebab',
    'Rajma Kebab',
    'Paneer Kebab',
    'Cheese Kebab',
    'Tandoori Paneer',
    'Soya Chaap Kebab',
    'Chaat',
    'Pani Puri (Golgappa)',
    'Dosa Carts',
    'Masala Dosa',
    'Schezwan Dosa',
    'Uttapam',
    'Idli-Vada',
    'Medu Vada',
    'Pav Bhaji',
    'Vada Pav',
    'Dabeli',
    'Misal Pav',
    'Samosa',
    'Aloo Samosa',
    'Paneer Samosa',
    'Mutton Samosa',
    'Keema Samosa',
    'Chole Bhature Shops',
    'Chole Kulche',
    'Kachori',
    'Aloo Kachori',
    'Pyaz Kachori',
    'Dahi Kachori',
    'Jalebi and Rabri',
    'Momos',
    'Veg Momos',
    'Chicken Momos',
    'Paneer Momos',
    'Fried Momos',
    'Steamed Momos',
    'Tandoori Momos',
    'Chole Tikki',
    'Aloo Tikki',
    'Bread Pakora',
    'Paneer Pakora',
    'Veg Pakora',
    'Onion Bhaji',
    'Palak Pakora',
    'Batata Vada',
    'Paniyaram',
    'Pesarattu',
    'Paratha',
    'Aloo Paratha',
    'Paneer Paratha',
    'Gobhi Paratha',
    'Methi Paratha',
    'Lachha Paratha',
    'Keema Paratha',
    'Egg Paratha',
    'Puri Sabzi',
    'Aloo Puri',
    'Bedmi Puri',
    'Dahi Puri',
    'Dahi Bhalla',
    'Papdi Chaat',
    'Aloo Chaat Carts',
    'Fruit Chaat Carts',
    'Bhel Puri Carts',
    'Sev Puri',
    'Ragda Pattice',
    'Dhokla',
    'Khandvi',
    'Fafda',
    'Jalebi Fafda',
    'Chana Jor Garam Carts',
    'Murukku',
    'Namkeen',
    'Aloo Chips',
    'Banana Chips',
    'Sweet Corn',
    'Masala Corn Carts',
    'Roasted Peanut',
    'Boiled Peanut',
    'Fried Rice',
    'Schezwan Fried Rice',
    'Egg Fried Rice',
    'Chicken Fried Rice',
    'Veg Noodles',
    'Hakka Noodles',
    'Schezwan Noodles',
    'Chow Mein',
    'Chicken Chow Mein',
    'Veg Manchurian',
    'Chicken Manchurian',
    'Gobi Manchurian',
    'Paneer Manchurian',
    'Tandoori Chicken',
    'Chicken Tikka',
    'Paneer Tikka',
    'Seekh Kebab',
    'Shami Kebab',
    'Shawarma',
    'Kathi Roll',
    'Chicken Kathi Roll',
    'Paneer Kathi Roll',
    'Egg Roll',
    'Chicken Egg Roll',
    'Frankie',
    'Chicken Frankie',
    'Paneer Frankie',
    'Fish Fry',
    'Pomfret Fry',
    'Bombil Fry',
    'Fish Cutlet',
    'Chicken Cutlet',
    'Vegetable Cutlet',
    'Keema Cutlet',
    'Paneer Cutlet',
    'Prawn Fry',
    'Prawn Curry',
    'Crab Fry',
    'Crab Curry',
    'Egg Bhurji',
    'Paneer Bhurji',
    'Anda Curry',
    'Anda Ghotala',
    'Baida Roti',
    'Mutton Biryani',
    'Chicken Biryani',
    'Veg Biryani',
    'Egg Biryani',
    'Pulao',
    'Veg Pulao',
    'Paneer Pulao',
    'Chicken Pulao',
    'Mutton Pulao',
    'Tandoori Roti',
    'Rumali Roti',
    'Butter Naan',
    'Plain Naan',
    'Garlic Naan',
    'Chur Chur Naan',
    'Naan Tandoori',
    'Paneer Butter Masala',
    'Kadhai Paneer',
    'Palak Paneer',
    'Butter Chicken',
    'Chicken Curry',
    'Mutton Curry',
    'Fish Curry',
    'Dal Makhani',
    'Rajma Chawal',
    'Chole Chawal',
    'Kadhi Chawal',
    'Paya Soup',
    'Nihari',
    'Bheja Fry',
    'Keema Pav',
    'Bhaji Pav',
    'Pav Kebab',
    'Sabudana Khichdi',
    'Sabudana Vada',
    'Sattu Sharbat',
    'Sattu Paratha',
    'Poha',
    'Upma',
    'Sheera',
    'Vermicelli Upma',
    'Lemon Rice',
    'Curd Rice',
    'Puliyogare',
    'Bisibelebath',
    'Rasam Rice',
    'Dal Rice',
    'Litti Chokha',
    'Roti Sabzi',
    'Chole Kulcha',
    'Thali Meals',
    'Gujarati Thali',
    'Rajasthani Thali',
    'South Indian Thali',
    'North Indian Thali',
    'Punjabi Thali',
    'Bengali Thali',
    'Assamese Thali',
    'Fish Thali',
    'Chicken Thali',
    'Veg Thali',
    'Dal Baati Churma',
    'Gatta Curry',
    'Rajasthani Kadhi',
    'Mawa Kachori',
    'Doodh Jalebi',
    'Rasgulla',
    'Gulab Jamun',
    'Ras Malai',
    'Kheer',
    'Seviyan Kheer',
    'Phirni',
    'Halwa',
    'Moong Dal Halwa',
    'Gajar Ka Halwa',
    'Badam Halwa',
    'Besan Laddu',
    'Moti Choor Laddu',
    'Boondi Laddu',
    'Barfi',
    'Kaju Katli',
    'Peda',
    'Kalakand',
    'Sandesh',
    'Cham Cham',
    'Malpua',
    'Balushahi',
    'Imarti',
    'Rabri Malpua',
    'Shrikhand',
    'Kulfi',
    'Falooda',
    'Ice Cream',
    'Matka Kulfi',
    'Gola',
    'Sugarcane Juice',
    'Coconut Water',
    'Lassi',
    'Chaas',
    'Buttermilk',
    'Thandai',
    'Sharbat',
    'Jal Jeera',
    'Aam Panna',
    'Nimbu Pani',
    'Rooh Afza',
    'Cold Coffee',
    'Tea (Chai)',
    'Masala Chai',
    'Ginger Tea',
    'Lemon Tea',
    'Green Tea',
    'Iced Tea',
    'Filter Coffee',
    'South Indian Coffee',
    'Kulhad Tea',
    'Milkshake',
    'Banana Shake',
    'Strawberry Shake',
    'Mango Shake',
    'Papaya Shake',
    'Chikoo Shake',
    'Smoothie',
    'Fruit Juice',
    'Mausambi Juice',
    'Orange Juice',
    'Watermelon Juice',
    'Pineapple Juice',
    'Mixed Fruit Juice',
    'Carrot Juice',
    'Beetroot Juice',
    'Karela Juice',
    'Aloe Vera Juice',
    'Veg Sandwich',
    'Cheese Sandwich',
    'Grilled Sandwich',
    'Club Sandwich',
    'Chicken Sandwich',
    'Paneer Sandwich',
    'Toast Butter',
    'Toast Jam',
    'Peanut Butter Toast',
    'Masala Toast',
    'Bombay Sandwich',
    'Burger',
    'Veg Burger',
    'Cheese Burger',
    'Chicken Burger',
    'Paneer Burger',
    'Mushroom Burger',
    'Pizza',
    'Veg Pizza',
    'Cheese Pizza',
    'Paneer Pizza',
    'Chicken Pizza',
    'Pepperoni Pizza',
    'Garlic Bread',
    'Pasta',
    'White Sauce Pasta',
    'Red Sauce Pasta',
    'Cheese Pasta',
    'Arrabbiata Pasta',
    'Aglio e Olio Pasta',
    'Mac and Cheese',
    'Spring Roll',
    'Veg Spring Roll',
    'Paneer Spring Roll',
    'Chicken Spring Roll',
    'Schezwan Spring Roll',
    'Veg Puff',
    'Paneer Puff',
    'Egg Puff',
    'Chicken Puff',
    'Croissant',
    'Patty',
    'Chocolate Brownie',
    'Donut',
    'Waffle',
    'Pancake',
    'Crepe',
    'French Toast',
    'Pudding',
    'Custard',
    'Tapioca Pudding',
    'Bread Pudding',
    'Banoffee Pie',
    'Apple Pie',
    'Fruit Tart',
    'Chocolate Mousse',
    'Truffle Cake',
    'Black Forest Cake',
    'Pineapple Cake',
    'Red Velvet Cake',
    'Chocolate Chip Cookies',
    'Biscuit',
    'Nankhatai',
    'Samosa Pav',
    'Bhel Sandwich',
    'Soya Chaap',
    'Paneer Chaap',
    'Malai Chaap',
    'Soya Seekh Kebab',
    'Stuffed Paratha',
    'Litti Chokha',
    'Golgappa',
    'Bhalla Papdi',
    'Lassi Stall',
    'Jalebi Cart',
    'Paniyaram Stall',
    'Tea Cart',
    'Biscuit Stall',
    'Bonda',
    'Masala Kachori',
    'Paan Shops',
    'Banana Chips Cart',
    'Chicken Shawarma',
    'Mutton Shawarma',
    'Vegetarian Shawarma',
    'Dry Fruit Shops',
    'Kulfi',
    'Falooda',
    'Tandoori Chicken',
    'Paneer Tikka',
    'Fish Fry',
    'Chole Bhature',
    'Puri Bhaji',
    'Sweet Corn',
    'Fruit Juice',
    'Egg Roll',
    'Masala Pav',
    'Schezwan Dosa',
    'Tawa Pulao',
    'Chana Jor Garam',
    'Frankie',
    'Baked Goods',
    'Onion Bhajji',
    'Peanut Brittle',
    'Banana Fritters',
    'Vegetable Pulao',
    'Paneer Butter Masala',
    'Chicken Curry',
    'Prawn Curry',
    'Mutton Curry',
    'Roti',
    'Rice',
    'Daal Fry',
    'Kofta Curry',
    'Keema Pav',
    'Fish Tikka',
    'Chicken Tikka',
    'Bhutta (Roasted Corn)',
    'Chai',
    'Matka Chai',
    'Kebab',
    'Veg Kebab',
    'Pav Bhaji',
    'Puri Chole',
    'Tandoori Paratha',
    'Roomali Roti',
    'Naan',
    'Garlic Naan',
    'Plain Roti',
    'Aloo Paratha',
    'Veg Biryani',
    'Chicken Biryani',
    'Paneer Biryani',
    'Vegetable Khichdi',
    'Raita',
    'Chole',
    'Rajma Chawal',
    'Kachori Chaat',
    'Pani Puri',
    'Bombay Sandwich',
    'Egg Fried Rice',
    'Chicken Manchurian',
    'Chicken Noodles',
    'Chicken Shawarma',
    'Vegetable Spring Roll',
    'Chai Wallah',
    'Tandoori Roti Wallah',
    'Dabeli',
    'Mithai',
    'Falooda Shops',
]
