# Generated by Django 5.1.1 on 2024-11-20 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatassistantconversationroom',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Conversation Rooms'},
        ),
        migrations.RemoveField(
            model_name='chatassistantconversationroom',
            name='is_coversation_end',
        ),
        migrations.AddField(
            model_name='chatassistantconversationroom',
            name='is_anonymous_user',
            field=models.BooleanField(default=False, help_text='Indicates if the user is anonymous.'),
        ),
        migrations.AddField(
            model_name='chatassistantconversationroom',
            name='is_conversation_end',
            field=models.BooleanField(default=False, help_text='Indicates if the conversation has ended.'),
        ),
        migrations.AlterField(
            model_name='chatassistantconversationroom',
            name='assistant',
            field=models.ForeignKey(blank=True, help_text='The assistant participating in the conversation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatassistantconversationroom',
            name='room_id',
            field=models.CharField(blank=True, help_text='Unique identifier for the conversation room.', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='chatassistantconversationroom',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user participating in the conversation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
